
[functions.whatsapp-bot-items]
enabled = true
verify_jwt = true
import_map = "./functions/whatsapp-bot-items/deno.json"
entrypoint = "./functions/whatsapp-bot-items/index.ts"

[functions.whatsapp-bot-orders]
enabled = true
verify_jwt = true
import_map = "./functions/whatsapp-bot-orders/deno.json"
entrypoint = "./functions/whatsapp-bot-orders/index.ts"

[functions.whatsapp-bot-sessions]
enabled = true
verify_jwt = true
import_map = "./functions/whatsapp-bot-sessions/deno.json"
entrypoint = "./functions/whatsapp-bot-sessions/index.ts"
