
[functions.whatsapp-bot-items]
enabled = true
verify_jwt = true
import_map = "./functions/whatsapp-bot-items/deno.json"
entrypoint = "./functions/whatsapp-bot-items/index.ts"

[functions.whatsapp-bot-orders]
enabled = true
verify_jwt = true
import_map = "./functions/whatsapp-bot-orders/deno.json"
entrypoint = "./functions/whatsapp-bot-orders/index.ts"

[functions.whatsapp-bot-sessions]
enabled = true
verify_jwt = true
import_map = "./functions/whatsapp-bot-sessions/deno.json"
entrypoint = "./functions/whatsapp-bot-sessions/index.ts"

[functions.whatsapp-cities]
enabled = true
verify_jwt = true
import_map = "./functions/whatsapp-cities/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/whatsapp-cities/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/whatsapp-cities/*.html" ]
