CREATE TABLE IF NOT EXISTS "public"."customers" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "type" "text" NOT NULL,
    "company_name" "text",
    "contact_name" "text",
    "full_name" "text",
    "email" "text",
    "phone" "text",
    "street" "text",
    "city" "text",
    "postal" "text",
    "country" "text",
    "is_active" boolean DEFAULT true NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "address_line_1" "text",
    "address_line_2" "text",
    "company_id" "uuid",
    "city_id" "uuid",
    "phone_2" "text",
    "map_location" "text",
    CONSTRAINT "customers_type_check" CHECK (("type" = ANY (ARRAY['company'::"text", 'individual'::"text"])))
);
CREATE TABLE IF NOT EXISTS "public"."products" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "company_id" "uuid" NOT NULL,
    "user_id" "uuid" NOT NULL,
    "sku" "text",
    "name" "text" NOT NULL,
    "description" "text",
    "unit" "text" DEFAULT 'ea'::"text" NOT NULL,
    "cost_price" numeric DEFAULT 0 NOT NULL,
    "sale_price" numeric DEFAULT 0 NOT NULL,
    "currency" "text" DEFAULT 'MUR'::"text" NOT NULL,
    "is_active" boolean DEFAULT true NOT NULL,
    "image_base64" "text",
    "image_mime_type" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "products_cost_price_check" CHECK (("cost_price" >= (0)::numeric)),
    CONSTRAINT "products_image_base64_size_check" CHECK ((("image_base64" IS NULL) OR ("octet_length"("image_base64") <= 5242880))),
    CONSTRAINT "products_image_mime_type_check" CHECK ((("image_mime_type" IS NULL) OR ("image_mime_type" = ANY (ARRAY['image/png'::"text", 'image/jpeg'::"text", 'image/webp'::"text", 'image/gif'::"text", 'image/svg+xml'::"text"])))),
    CONSTRAINT "products_sale_price_check" CHECK (("sale_price" >= (0)::numeric))
);
CREATE TABLE IF NOT EXISTS "public"."sales_orders" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "customer_id" "uuid",
    "created_from_quotation_id" "uuid",
    "number" "text" NOT NULL,
    "issue_date" "date" DEFAULT CURRENT_DATE NOT NULL,
    "valid_until" "date" NOT NULL,
    "status" "public"."sales_order_status" DEFAULT 'active'::"public"."sales_order_status" NOT NULL,
    "currency" "text" DEFAULT 'MUR'::"text" NOT NULL,
    "from_snapshot" "jsonb" NOT NULL,
    "bill_to_snapshot" "jsonb" NOT NULL,
    "client_snapshot" "jsonb",
    "subtotal" numeric DEFAULT 0 NOT NULL,
    "tax_total" numeric DEFAULT 0 NOT NULL,
    "discount_type" "text",
    "discount_amount" numeric DEFAULT 0 NOT NULL,
    "shipping_amount" numeric DEFAULT 0 NOT NULL,
    "total" numeric DEFAULT 0 NOT NULL,
    "notes" "text",
    "terms" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "company_id" "uuid" NOT NULL,
    "fulfillment_status" "public"."sales_order_fulfillment_status" DEFAULT 'new'::"public"."sales_order_fulfillment_status" NOT NULL,
    "payment_status" "public"."sales_order_payment_status" DEFAULT 'unpaid'::"public"."sales_order_payment_status" NOT NULL,
    "city_id" "uuid",
    "delivery_date" "date",
    "active_driver_delivery_id" "uuid",
    CONSTRAINT "sales_orders_discount_type_check" CHECK (("discount_type" = ANY (ARRAY['value'::"text", 'percent'::"text"])))
);
CREATE TABLE IF NOT EXISTS "public"."cities" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "company_id" "uuid" NOT NULL,
    "name" "text" NOT NULL,
    "is_active" boolean DEFAULT true NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "region" "text",
    CONSTRAINT "cities_region_check" CHECK ((("region" IS NULL) OR ("region" = ANY (ARRAY['North'::"text", 'East'::"text", 'South'::"text", 'West'::"text", 'Center'::"text"]))))
);
CREATE TABLE IF NOT EXISTS "public"."city_aliases" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "city_id" "uuid" NOT NULL,
    "alias" "text" NOT NULL,
    "normalized_alias" "text" NOT NULL,
    "source" "text" DEFAULT 'manual'::"text",
    "created_at" timestamp with time zone DEFAULT "now"()
);
CREATE TABLE IF NOT EXISTS "public"."city_match_logs" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "raw_address" "text" NOT NULL,
    "normalized_address" "text",
    "predicted_city_id" "uuid",
    "confirmed_city_id" "uuid",
    "predicted_score" numeric,
    "was_correct" boolean,
    "whatsapp_user_id" "text",
    "created_at" timestamp with time zone DEFAULT "now"()
);
CREATE TABLE IF NOT EXISTS "public"."companies" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "owner_user_id" "uuid" NOT NULL,
    "name" "text" NOT NULL,
    "brn" "text",
    "vat_number" "text",
    "email" "text",
    "phone" "text",
    "address_line_1" "text",
    "address_line_2" "text",
    "city" "text",
    "country" "text",
    "plan_id" "uuid" NOT NULL,
    "subscription_start_date" "date" DEFAULT CURRENT_DATE NOT NULL,
    "subscription_end_date" "date",
    "is_trial" boolean DEFAULT false,
    "max_users_override" integer,
    "billing_contact_name" "text",
    "billing_contact_email" "text",
    "billing_contact_phone" "text",
    "is_active" boolean DEFAULT true NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "company_code" "text" NOT NULL,
    "company_logo_url" "text"
);
CREATE TABLE IF NOT EXISTS "public"."company_roles" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "company_id" "uuid" NOT NULL,
    "name" "text" NOT NULL,
    "description" "text",
    "is_system" boolean DEFAULT false,
    "is_active" boolean DEFAULT true NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"()
);
CREATE TABLE IF NOT EXISTS "public"."company_users" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "company_id" "uuid" NOT NULL,
    "user_id" "uuid" NOT NULL,
    "role_id" "uuid" NOT NULL,
    "is_owner" boolean DEFAULT false NOT NULL,
    "is_active" boolean DEFAULT true NOT NULL,
    "invited_at" timestamp with time zone,
    "joined_at" timestamp with time zone DEFAULT "now"(),
    "driver_rate" numeric(12,2),
    CONSTRAINT "company_users_driver_rate_non_negative" CHECK ((("driver_rate" IS NULL) OR ("driver_rate" >= (0)::numeric)))
);
CREATE TABLE IF NOT EXISTS "public"."credit_note_items" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "credit_note_id" "uuid" NOT NULL,
    "company_id" "uuid",
    "product_id" "uuid",
    "item" "text" NOT NULL,
    "description" "text",
    "quantity" numeric(14,4) DEFAULT 1 NOT NULL,
    "unit_price" numeric(14,2) DEFAULT 0 NOT NULL,
    "tax_percent" numeric(8,4) DEFAULT 0 NOT NULL,
    "line_subtotal" numeric(14,2) DEFAULT 0 NOT NULL,
    "line_tax" numeric(14,2) DEFAULT 0 NOT NULL,
    "line_total" numeric(14,2) DEFAULT 0 NOT NULL,
    "sort_order" integer DEFAULT 0 NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "invoice_item_id" "uuid"
);
CREATE TABLE IF NOT EXISTS "public"."credit_notes" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "number" "text" NOT NULL,
    "company_id" "uuid",
    "user_id" "uuid" NOT NULL,
    "customer_id" "uuid",
    "related_invoice_id" "uuid",
    "issue_date" "date" DEFAULT CURRENT_DATE NOT NULL,
    "status" "public"."credit_note_status" DEFAULT 'issued'::"public"."credit_note_status" NOT NULL,
    "currency" "text" DEFAULT 'MUR'::"text" NOT NULL,
    "subtotal" numeric(14,2) DEFAULT 0 NOT NULL,
    "tax_total" numeric(14,2) DEFAULT 0 NOT NULL,
    "total" numeric(14,2) DEFAULT 0 NOT NULL,
    "discount_type" "text" DEFAULT 'value'::"text" NOT NULL,
    "discount_amount" numeric(14,2) DEFAULT 0 NOT NULL,
    "reason" "text",
    "notes" "text",
    "terms" "text",
    "from_snapshot" "jsonb",
    "bill_to_snapshot" "jsonb",
    "client_snapshot" "jsonb",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "credit_type" "text" DEFAULT 'partial'::"text" NOT NULL,
    CONSTRAINT "credit_notes_credit_type_check" CHECK (("credit_type" = ANY (ARRAY['full'::"text", 'partial'::"text"]))),
    CONSTRAINT "credit_notes_discount_type_check" CHECK (("discount_type" = ANY (ARRAY['value'::"text", 'percent'::"text"])))
);
CREATE TABLE IF NOT EXISTS "public"."customer_credit_balances" (
    "user_id" "uuid" NOT NULL,
    "customer_id" "uuid" NOT NULL,
    "balance" numeric DEFAULT 0 NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "company_id" "uuid",
    CONSTRAINT "customer_credit_balances_balance_check" CHECK (("balance" >= (0)::numeric))
);
CREATE TABLE IF NOT EXISTS "public"."customer_credit_settlements" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "customer_id" "uuid" NOT NULL,
    "invoice_id" "uuid",
    "amount" numeric NOT NULL,
    "notes" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "company_id" "uuid",
    CONSTRAINT "customer_credit_settlements_amount_check" CHECK (("amount" > (0)::numeric))
);
CREATE TABLE IF NOT EXISTS "public"."deliveries" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "company_id" "uuid" NOT NULL,
    "driver_user_id" "uuid" NOT NULL,
    "created_by" "uuid" NOT NULL,
    "notes" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "status" "public"."delivery_note_status" DEFAULT 'new'::"public"."delivery_note_status" NOT NULL,
    "driver_status" boolean,
    "delivery_date" "date",
    "from_location_id" "uuid",
    "location_id" "uuid",
    "delivered_to_driver_at" timestamp with time zone,
    "driver_settlement_status" "public"."driver_settlement_status" DEFAULT 'pending'::"public"."driver_settlement_status" NOT NULL
);
CREATE TABLE IF NOT EXISTS "public"."delivery_driver_settlements" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "company_id" "uuid" NOT NULL,
    "delivery_id" "uuid" NOT NULL,
    "driver_user_id" "uuid" NOT NULL,
    "recorded_by" "uuid" NOT NULL,
    "amount_to_owner" numeric(14,2) NOT NULL,
    "currency" "text" DEFAULT 'MUR'::"text" NOT NULL,
    "settlement_cash_total" numeric(14,2),
    "driver_daily_rate" numeric(14,2),
    "linked_orders_total" numeric(14,2),
    "bank_reference" "text",
    "expense_id" "uuid",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "cash_amount" numeric(14,2) DEFAULT 0 NOT NULL,
    "bank_transfer_amount" numeric(14,2) DEFAULT 0 NOT NULL,
    "due_amount" numeric(14,2) DEFAULT 0 NOT NULL,
    CONSTRAINT "delivery_driver_settlements_split_ck" CHECK (((("amount_to_owner" <= (0)::numeric) AND ("cash_amount" = (0)::numeric) AND ("bank_transfer_amount" = (0)::numeric) AND ("due_amount" = (0)::numeric)) OR (("amount_to_owner" > (0)::numeric) AND ("cash_amount" >= (0)::numeric) AND ("bank_transfer_amount" >= (0)::numeric) AND ("due_amount" >= (0)::numeric) AND ("round"((("cash_amount" + "bank_transfer_amount") + "due_amount"), 2) = "round"(("amount_to_owner")::numeric, 2)))))
);
CREATE TABLE IF NOT EXISTS "public"."delivery_sales_orders" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "delivery_id" "uuid" NOT NULL,
    "sales_order_id" "uuid" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "is_active" boolean DEFAULT true NOT NULL,
    "deactivated_at" timestamp with time zone,
    "deactivation_reason" "text"
);
CREATE TABLE IF NOT EXISTS "public"."delivery_upselling_commissions" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "company_id" "uuid" NOT NULL,
    "delivery_id" "uuid" NOT NULL,
    "sales_order_id" "uuid" NOT NULL,
    "commission_amount" numeric DEFAULT 0 NOT NULL,
    "currency" "text" DEFAULT 'MUR'::"text" NOT NULL,
    "recorded_by" "uuid" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "delivery_upselling_commissions_commission_amount_check" CHECK (("commission_amount" >= (0)::numeric))
);
CREATE TABLE IF NOT EXISTS "public"."driver_credit_balances" (
    "user_id" "uuid" NOT NULL,
    "driver_user_id" "uuid" NOT NULL,
    "company_id" "uuid" NOT NULL,
    "balance" numeric(14,2) DEFAULT 0 NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);
CREATE TABLE IF NOT EXISTS "public"."driver_credit_settlements" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "company_id" "uuid",
    "driver_user_id" "uuid" NOT NULL,
    "delivery_id" "uuid",
    "amount" numeric(14,2) NOT NULL,
    "notes" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);
CREATE TABLE IF NOT EXISTS "public"."employee_advances" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "employee_id" "uuid" NOT NULL,
    "amount" numeric(12,2) NOT NULL,
    "amount_deducted" numeric(12,2) DEFAULT 0 NOT NULL,
    "deduction_per_period" numeric(12,2) NOT NULL,
    "status" "text" DEFAULT 'active'::"text" NOT NULL,
    "notes" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "company_id" "uuid",
    CONSTRAINT "employee_advances_status_check" CHECK (("status" = ANY (ARRAY['active'::"text", 'fully_deducted'::"text"])))
);
CREATE TABLE IF NOT EXISTS "public"."employees" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "full_name" "text" NOT NULL,
    "phone" "text",
    "email" "text",
    "position" "text",
    "basic_salary" numeric(12,2) DEFAULT 0 NOT NULL,
    "payment_type" "text" DEFAULT 'monthly'::"text" NOT NULL,
    "join_date" "date" DEFAULT CURRENT_DATE NOT NULL,
    "status" "text" DEFAULT 'active'::"text" NOT NULL,
    "transport_allowance" numeric(12,2) DEFAULT 0 NOT NULL,
    "other_allowance" numeric(12,2) DEFAULT 0 NOT NULL,
    "currency" "text" DEFAULT 'MUR'::"text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "company_id" "uuid",
    CONSTRAINT "employees_payment_type_check" CHECK (("payment_type" = ANY (ARRAY['monthly'::"text", 'daily'::"text", 'hourly'::"text"]))),
    CONSTRAINT "employees_status_check" CHECK (("status" = ANY (ARRAY['active'::"text", 'inactive'::"text"])))
);
CREATE TABLE IF NOT EXISTS "public"."expense_items" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "expense_id" "uuid" NOT NULL,
    "item" "text" NOT NULL,
    "description" "text",
    "quantity" numeric NOT NULL,
    "unit_price" numeric NOT NULL,
    "tax_percent" numeric DEFAULT 0 NOT NULL,
    "line_subtotal" numeric DEFAULT 0 NOT NULL,
    "line_tax" numeric DEFAULT 0 NOT NULL,
    "line_total" numeric DEFAULT 0 NOT NULL,
    "company_id" "uuid",
    CONSTRAINT "expense_items_quantity_check" CHECK (("quantity" >= (0)::numeric)),
    CONSTRAINT "expense_items_tax_percent_check" CHECK (("tax_percent" >= (0)::numeric)),
    CONSTRAINT "expense_items_unit_price_check" CHECK (("unit_price" >= (0)::numeric))
);
CREATE TABLE IF NOT EXISTS "public"."expenses" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "description" "text" NOT NULL,
    "amount" numeric NOT NULL,
    "currency" "text" DEFAULT 'MUR'::"text" NOT NULL,
    "category" "text",
    "expense_date" "date" DEFAULT CURRENT_DATE NOT NULL,
    "payment_method" "text",
    "invoice_id" "uuid",
    "notes" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "line_items" "jsonb" DEFAULT '[]'::"jsonb",
    "company_id" "uuid",
    CONSTRAINT "expenses_amount_check" CHECK (("amount" >= (0)::numeric)),
    CONSTRAINT "expenses_payment_method_check" CHECK (("payment_method" = ANY (ARRAY['Cash'::"text", 'Card Payment'::"text", 'Credit Facilities'::"text"])))
);
CREATE TABLE IF NOT EXISTS "public"."features" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "code" "text" NOT NULL,
    "name" "text" NOT NULL,
    "description" "text",
    "is_active" boolean DEFAULT true NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);
CREATE TABLE IF NOT EXISTS "public"."inventory_movements" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "company_id" "uuid" NOT NULL,
    "user_id" "uuid" NOT NULL,
    "product_id" "uuid" NOT NULL,
    "event_type" "text" NOT NULL,
    "from_location_id" "uuid",
    "to_location_id" "uuid",
    "quantity" numeric NOT NULL,
    "note" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "delivery_id" "uuid",
    "sales_order_id" "uuid",
    "reference_type" "text",
    "reference_number" "text",
    CONSTRAINT "inventory_movements_adjustment_out_shape" CHECK ((("event_type" IS DISTINCT FROM 'adjustment_out'::"text") OR (("from_location_id" IS NOT NULL) AND ("to_location_id" IS NULL)))),
    CONSTRAINT "inventory_movements_event_type_check" CHECK (("event_type" = ANY (ARRAY['transfer'::"text", 'refill'::"text", 'adjustment_out'::"text"]))),
    CONSTRAINT "inventory_movements_quantity_check" CHECK (("quantity" > (0)::numeric)),
    CONSTRAINT "inventory_movements_refill_shape" CHECK ((("event_type" IS DISTINCT FROM 'refill'::"text") OR (("to_location_id" IS NOT NULL) AND ("from_location_id" IS NULL)))),
    CONSTRAINT "inventory_movements_transfer_shape" CHECK ((("event_type" IS DISTINCT FROM 'transfer'::"text") OR (("from_location_id" IS NOT NULL) AND ("to_location_id" IS NOT NULL) AND ("from_location_id" IS DISTINCT FROM "to_location_id"))))
);
CREATE TABLE IF NOT EXISTS "public"."locations" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "company_id" "uuid" NOT NULL,
    "user_id" "uuid" NOT NULL,
    "name" "text" NOT NULL,
    "code" "text",
    "description" "text",
    "address_line_1" "text",
    "address_line_2" "text",
    "city" "text",
    "postal" "text",
    "country" "text",
    "is_active" boolean DEFAULT true NOT NULL,
    "is_default" boolean DEFAULT false NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "map_link" "text",
    "location_type" "public"."location_type" DEFAULT 'warehouse'::"public"."location_type" NOT NULL,
    "parent_location_id" "uuid",
    "is_stock_location" boolean DEFAULT true NOT NULL,
    "is_primary_warehouse" boolean DEFAULT false NOT NULL,
    CONSTRAINT "locations_primary_warehouse_type_check" CHECK ((("is_primary_warehouse" = false) OR ("location_type" = 'warehouse'::"public"."location_type")))
);
CREATE TABLE IF NOT EXISTS "public"."product_location_stocks" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "company_id" "uuid" NOT NULL,
    "product_id" "uuid" NOT NULL,
    "location_id" "uuid" NOT NULL,
    "quantity" numeric DEFAULT 0 NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "product_location_stocks_quantity_check" CHECK (("quantity" >= (0)::numeric))
);
CREATE TABLE IF NOT EXISTS "public"."invoice_items" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "invoice_id" "uuid" NOT NULL,
    "item" "text" NOT NULL,
    "description" "text",
    "quantity" numeric(12,3) NOT NULL,
    "unit_price" numeric(12,2) NOT NULL,
    "tax_percent" numeric(5,2) DEFAULT 0 NOT NULL,
    "line_subtotal" numeric(12,2) DEFAULT 0 NOT NULL,
    "line_tax" numeric(12,2) DEFAULT 0 NOT NULL,
    "line_total" numeric(12,2) DEFAULT 0 NOT NULL,
    "company_id" "uuid",
    "product_id" "uuid",
    CONSTRAINT "invoice_items_quantity_check" CHECK (("quantity" >= (0)::numeric)),
    CONSTRAINT "invoice_items_tax_percent_check" CHECK (("tax_percent" >= (0)::numeric)),
    CONSTRAINT "invoice_items_unit_price_check" CHECK (("unit_price" >= (0)::numeric))
);
CREATE TABLE IF NOT EXISTS "public"."invoices" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "customer_id" "uuid",
    "number" "text" NOT NULL,
    "issue_date" "date" DEFAULT CURRENT_DATE NOT NULL,
    "due_date" "date" NOT NULL,
    "status" "public"."invoice_status" DEFAULT 'unpaid'::"public"."invoice_status" NOT NULL,
    "currency" "text" DEFAULT 'MUR'::"text" NOT NULL,
    "from_snapshot" "jsonb" NOT NULL,
    "bill_to_snapshot" "jsonb" NOT NULL,
    "subtotal" numeric(12,2) DEFAULT 0 NOT NULL,
    "tax_total" numeric(12,2) DEFAULT 0 NOT NULL,
    "discount_type" "text",
    "discount_amount" numeric(12,2) DEFAULT 0 NOT NULL,
    "shipping_amount" numeric(12,2) DEFAULT 0 NOT NULL,
    "total" numeric(12,2) DEFAULT 0 NOT NULL,
    "notes" "text",
    "terms" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "client_snapshot" "jsonb",
    "payment_method" "text",
    "amount_paid" numeric DEFAULT 0 NOT NULL,
    "amount_due" numeric DEFAULT 0 NOT NULL,
    "credit_applied" numeric DEFAULT 0 NOT NULL,
    "created_from_quotation_id" "uuid",
    "created_from_sales_order_id" "uuid",
    "company_id" "uuid",
    CONSTRAINT "invoices_amount_due_check" CHECK (("amount_due" >= (0)::numeric)),
    CONSTRAINT "invoices_amount_paid_check" CHECK (("amount_paid" >= (0)::numeric)),
    CONSTRAINT "invoices_credit_applied_check" CHECK (("credit_applied" >= (0)::numeric)),
    CONSTRAINT "invoices_discount_type_check" CHECK (("discount_type" = ANY (ARRAY['value'::"text", 'percent'::"text"]))),
    CONSTRAINT "invoices_payment_method_check" CHECK (("payment_method" = ANY (ARRAY['Cash'::"text", 'Card Payment'::"text", 'Credit Facilities'::"text"]))),
    CONSTRAINT "invoices_status_check" CHECK ((("status")::"text" = ANY (ARRAY['unpaid'::"text", 'paid'::"text", 'cancelled'::"text"])))
);
CREATE TABLE IF NOT EXISTS "public"."location_drivers" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "company_id" "uuid" NOT NULL,
    "location_id" "uuid" NOT NULL,
    "driver_user_id" "uuid" NOT NULL,
    "is_primary" boolean DEFAULT false NOT NULL,
    "is_active" boolean DEFAULT true NOT NULL,
    "assigned_from" "date" DEFAULT CURRENT_DATE NOT NULL,
    "assigned_until" "date",
    "notes" "text",
    "created_by" "uuid",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "location_drivers_check" CHECK ((("assigned_until" IS NULL) OR ("assigned_until" >= "assigned_from")))
);
CREATE TABLE IF NOT EXISTS "public"."payroll_runs" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "month" smallint NOT NULL,
    "year" smallint NOT NULL,
    "status" "text" DEFAULT 'draft'::"text" NOT NULL,
    "total_gross" numeric(12,2) DEFAULT 0 NOT NULL,
    "total_deductions" numeric(12,2) DEFAULT 0 NOT NULL,
    "total_net" numeric(12,2) DEFAULT 0 NOT NULL,
    "currency" "text" DEFAULT 'MUR'::"text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "company_id" "uuid",
    CONSTRAINT "payroll_runs_month_check" CHECK ((("month" >= 1) AND ("month" <= 12))),
    CONSTRAINT "payroll_runs_status_check" CHECK (("status" = ANY (ARRAY['draft'::"text", 'processed'::"text"]))),
    CONSTRAINT "payroll_runs_year_check" CHECK ((("year" >= 2020) AND ("year" <= 2100)))
);
CREATE TABLE IF NOT EXISTS "public"."payslip_advance_deductions" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "payslip_id" "uuid" NOT NULL,
    "advance_id" "uuid" NOT NULL,
    "amount" numeric(12,2) NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "company_id" "uuid"
);
CREATE TABLE IF NOT EXISTS "public"."payslips" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "payroll_run_id" "uuid" NOT NULL,
    "employee_id" "uuid" NOT NULL,
    "basic_salary" numeric(12,2) NOT NULL,
    "transport_allowance" numeric(12,2) DEFAULT 0 NOT NULL,
    "other_allowance" numeric(12,2) DEFAULT 0 NOT NULL,
    "gross_salary" numeric(12,2) NOT NULL,
    "advance_deduction" numeric(12,2) DEFAULT 0 NOT NULL,
    "absence_deduction" numeric(12,2) DEFAULT 0 NOT NULL,
    "other_deduction" numeric(12,2) DEFAULT 0 NOT NULL,
    "total_deductions" numeric(12,2) DEFAULT 0 NOT NULL,
    "net_salary" numeric(12,2) NOT NULL,
    "payment_status" "text" DEFAULT 'unpaid'::"text" NOT NULL,
    "payment_method" "text",
    "payment_date" "date",
    "expense_id" "uuid",
    "notes" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "company_id" "uuid",
    CONSTRAINT "payslips_payment_method_check" CHECK ((("payment_method" IS NULL) OR ("payment_method" = ANY (ARRAY['Cash'::"text", 'Card Payment'::"text", 'Bank Transfer'::"text"])))),
    CONSTRAINT "payslips_payment_status_check" CHECK (("payment_status" = ANY (ARRAY['unpaid'::"text", 'paid'::"text"])))
);
CREATE TABLE IF NOT EXISTS "public"."plan_features" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "plan_id" "uuid" NOT NULL,
    "feature_id" "uuid" NOT NULL,
    "is_enabled" boolean DEFAULT true NOT NULL
);
CREATE TABLE IF NOT EXISTS "public"."plans" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "name" "text" NOT NULL,
    "description" "text",
    "price" numeric DEFAULT 0 NOT NULL,
    "currency" "text" DEFAULT 'MUR'::"text",
    "max_users" integer DEFAULT 1 NOT NULL,
    "billing_cycle" "text" NOT NULL,
    "is_active" boolean DEFAULT true NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "plans_billing_cycle_check" CHECK (("billing_cycle" = ANY (ARRAY['monthly'::"text", 'yearly'::"text"])))
);
CREATE TABLE IF NOT EXISTS "public"."preferences" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "number_prefix" "text" DEFAULT 'INV'::"text" NOT NULL,
    "number_padding" integer DEFAULT 5 NOT NULL,
    "next_number" integer DEFAULT 1 NOT NULL,
    "currency" "text" DEFAULT 'USD'::"text" NOT NULL,
    "payment_terms" integer DEFAULT 14 NOT NULL,
    "default_notes" "text",
    "default_terms" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "company_id" "uuid",
    CONSTRAINT "preferences_next_number_check" CHECK (("next_number" >= 1)),
    CONSTRAINT "preferences_number_padding_check" CHECK ((("number_padding" >= 1) AND ("number_padding" <= 10))),
    CONSTRAINT "preferences_payment_terms_check" CHECK (("payment_terms" >= 0))
);
CREATE TABLE IF NOT EXISTS "public"."profiles" (
    "id" "uuid" NOT NULL,
    "account_type" "text" DEFAULT 'company'::"text" NOT NULL,
    "company_name" "text",
    "logo_url" "text",
    "registration_id" "text",
    "full_name" "text",
    "tax_id" "text",
    "email" "text",
    "phone" "text",
    "street" "text",
    "city" "text",
    "postal" "text",
    "country" "text",
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "address_line_1" "text",
    "address_line_2" "text",
    "bank_name" "text",
    "bank_acc_num" "text",
    "vat_number" "text",
    "vat_registered" boolean DEFAULT false NOT NULL,
    CONSTRAINT "profiles_account_type_check" CHECK (("account_type" = ANY (ARRAY['company'::"text", 'individual'::"text"])))
);
CREATE TABLE IF NOT EXISTS "public"."purchase_invoice_items" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "purchase_invoice_id" "uuid" NOT NULL,
    "item" "text" NOT NULL,
    "description" "text",
    "quantity" numeric NOT NULL,
    "unit_price" numeric NOT NULL,
    "tax_percent" numeric DEFAULT 0 NOT NULL,
    "line_subtotal" numeric DEFAULT 0 NOT NULL,
    "line_tax" numeric DEFAULT 0 NOT NULL,
    "line_total" numeric DEFAULT 0 NOT NULL,
    "sort_order" integer DEFAULT 0 NOT NULL,
    "company_id" "uuid",
    CONSTRAINT "purchase_invoice_items_quantity_check" CHECK (("quantity" >= (0)::numeric)),
    CONSTRAINT "purchase_invoice_items_tax_percent_check" CHECK (("tax_percent" >= (0)::numeric)),
    CONSTRAINT "purchase_invoice_items_unit_price_check" CHECK (("unit_price" >= (0)::numeric))
);
CREATE TABLE IF NOT EXISTS "public"."purchase_invoices" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "supplier_id" "uuid",
    "number" "text" NOT NULL,
    "issue_date" "date" DEFAULT CURRENT_DATE NOT NULL,
    "due_date" "date" NOT NULL,
    "status" "public"."purchase_invoice_status" DEFAULT 'unpaid'::"public"."purchase_invoice_status" NOT NULL,
    "currency" "text" DEFAULT 'MUR'::"text" NOT NULL,
    "from_snapshot" "jsonb" DEFAULT '{}'::"jsonb" NOT NULL,
    "bill_to_snapshot" "jsonb" DEFAULT '{}'::"jsonb" NOT NULL,
    "client_snapshot" "jsonb",
    "subtotal" numeric DEFAULT 0 NOT NULL,
    "tax_total" numeric DEFAULT 0 NOT NULL,
    "discount_type" "text",
    "discount_amount" numeric DEFAULT 0 NOT NULL,
    "shipping_amount" numeric DEFAULT 0 NOT NULL,
    "total" numeric DEFAULT 0 NOT NULL,
    "notes" "text",
    "terms" "text",
    "payment_method" "text",
    "amount_paid" numeric DEFAULT 0 NOT NULL,
    "amount_due" numeric DEFAULT 0 NOT NULL,
    "created_from_purchase_order_id" "uuid",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "company_id" "uuid",
    CONSTRAINT "purchase_invoices_amount_due_check" CHECK (("amount_due" >= (0)::numeric)),
    CONSTRAINT "purchase_invoices_amount_paid_check" CHECK (("amount_paid" >= (0)::numeric)),
    CONSTRAINT "purchase_invoices_discount_type_check" CHECK (("discount_type" = ANY (ARRAY['value'::"text", 'percent'::"text"]))),
    CONSTRAINT "purchase_invoices_payment_method_check" CHECK ((("payment_method" IS NULL) OR ("payment_method" = ANY (ARRAY['Cash'::"text", 'Card Payment'::"text", 'Credit Facilities'::"text", 'Bank Transfer'::"text"]))))
);
CREATE TABLE IF NOT EXISTS "public"."purchase_order_items" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "purchase_order_id" "uuid" NOT NULL,
    "item" "text" NOT NULL,
    "description" "text",
    "quantity" numeric NOT NULL,
    "unit_price" numeric NOT NULL,
    "tax_percent" numeric DEFAULT 0 NOT NULL,
    "line_subtotal" numeric DEFAULT 0 NOT NULL,
    "line_tax" numeric DEFAULT 0 NOT NULL,
    "line_total" numeric DEFAULT 0 NOT NULL,
    "sort_order" integer DEFAULT 0 NOT NULL,
    "company_id" "uuid",
    CONSTRAINT "purchase_order_items_quantity_check" CHECK (("quantity" >= (0)::numeric)),
    CONSTRAINT "purchase_order_items_tax_percent_check" CHECK (("tax_percent" >= (0)::numeric)),
    CONSTRAINT "purchase_order_items_unit_price_check" CHECK (("unit_price" >= (0)::numeric))
);
CREATE TABLE IF NOT EXISTS "public"."purchase_orders" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "supplier_id" "uuid",
    "number" "text" NOT NULL,
    "issue_date" "date" DEFAULT CURRENT_DATE NOT NULL,
    "valid_until" "date" NOT NULL,
    "status" "public"."purchase_order_status" DEFAULT 'active'::"public"."purchase_order_status" NOT NULL,
    "currency" "text" DEFAULT 'MUR'::"text" NOT NULL,
    "from_snapshot" "jsonb" NOT NULL,
    "bill_to_snapshot" "jsonb" NOT NULL,
    "client_snapshot" "jsonb",
    "subtotal" numeric DEFAULT 0 NOT NULL,
    "tax_total" numeric DEFAULT 0 NOT NULL,
    "discount_type" "text",
    "discount_amount" numeric DEFAULT 0 NOT NULL,
    "shipping_amount" numeric DEFAULT 0 NOT NULL,
    "total" numeric DEFAULT 0 NOT NULL,
    "notes" "text",
    "terms" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "company_id" "uuid",
    CONSTRAINT "purchase_orders_discount_type_check" CHECK (("discount_type" = ANY (ARRAY['value'::"text", 'percent'::"text"])))
);
CREATE TABLE IF NOT EXISTS "public"."quotation_items" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "quotation_id" "uuid" NOT NULL,
    "item" "text" NOT NULL,
    "description" "text",
    "quantity" numeric NOT NULL,
    "unit_price" numeric NOT NULL,
    "tax_percent" numeric DEFAULT 0 NOT NULL,
    "line_subtotal" numeric DEFAULT 0 NOT NULL,
    "line_tax" numeric DEFAULT 0 NOT NULL,
    "line_total" numeric DEFAULT 0 NOT NULL,
    "sort_order" integer DEFAULT 0 NOT NULL,
    "company_id" "uuid",
    CONSTRAINT "quotation_items_quantity_check" CHECK (("quantity" >= (0)::numeric)),
    CONSTRAINT "quotation_items_tax_percent_check" CHECK (("tax_percent" >= (0)::numeric)),
    CONSTRAINT "quotation_items_unit_price_check" CHECK (("unit_price" >= (0)::numeric))
);
CREATE TABLE IF NOT EXISTS "public"."quotations" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "customer_id" "uuid",
    "number" "text" NOT NULL,
    "issue_date" "date" DEFAULT CURRENT_DATE NOT NULL,
    "valid_until" "date" NOT NULL,
    "status" "public"."quotation_status" DEFAULT 'active'::"public"."quotation_status" NOT NULL,
    "currency" "text" DEFAULT 'MUR'::"text" NOT NULL,
    "from_snapshot" "jsonb" NOT NULL,
    "bill_to_snapshot" "jsonb" NOT NULL,
    "client_snapshot" "jsonb",
    "subtotal" numeric DEFAULT 0 NOT NULL,
    "tax_total" numeric DEFAULT 0 NOT NULL,
    "discount_type" "text",
    "discount_amount" numeric DEFAULT 0 NOT NULL,
    "shipping_amount" numeric DEFAULT 0 NOT NULL,
    "total" numeric DEFAULT 0 NOT NULL,
    "notes" "text",
    "terms" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "company_id" "uuid",
    CONSTRAINT "quotations_discount_type_check" CHECK (("discount_type" = ANY (ARRAY['value'::"text", 'percent'::"text"])))
);
CREATE TABLE IF NOT EXISTS "public"."role_features" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "role_id" "uuid" NOT NULL,
    "feature_id" "uuid" NOT NULL
);
CREATE TABLE IF NOT EXISTS "public"."sales_order_items" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "sales_order_id" "uuid" NOT NULL,
    "item" "text" NOT NULL,
    "description" "text",
    "quantity" numeric NOT NULL,
    "unit_price" numeric NOT NULL,
    "tax_percent" numeric DEFAULT 0 NOT NULL,
    "line_subtotal" numeric DEFAULT 0 NOT NULL,
    "line_tax" numeric DEFAULT 0 NOT NULL,
    "line_total" numeric DEFAULT 0 NOT NULL,
    "sort_order" integer DEFAULT 0 NOT NULL,
    "company_id" "uuid",
    "product_id" "uuid",
    CONSTRAINT "sales_order_items_quantity_check" CHECK (("quantity" >= (0)::numeric)),
    CONSTRAINT "sales_order_items_tax_percent_check" CHECK (("tax_percent" >= (0)::numeric)),
    CONSTRAINT "sales_order_items_unit_price_check" CHECK (("unit_price" >= (0)::numeric))
);
CREATE TABLE IF NOT EXISTS "public"."suppliers" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "type" "text" DEFAULT 'company'::"text" NOT NULL,
    "company_name" "text",
    "contact_name" "text",
    "full_name" "text",
    "email" "text",
    "phone" "text",
    "street" "text",
    "city" "text",
    "postal" "text",
    "country" "text",
    "address_line_1" "text",
    "address_line_2" "text",
    "supplier_code" "text",
    "vat_number" "text",
    "registration_id" "text",
    "notes" "text",
    "is_active" boolean DEFAULT true NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "company_id" "uuid",
    CONSTRAINT "suppliers_type_check" CHECK (("type" = ANY (ARRAY['company'::"text", 'individual'::"text"])))
);
CREATE TABLE IF NOT EXISTS "public"."user_profiles" (
    "id" "uuid" NOT NULL,
    "full_name" "text",
    "email" "text",
    "phone" "text",
    "avatar_url" "text",
    "system_role" "public"."system_role" DEFAULT 'member'::"public"."system_role" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "is_active" boolean DEFAULT false NOT NULL
);
CREATE TABLE IF NOT EXISTS "public"."user_settings" (
    "user_id" "uuid" NOT NULL,
    "currency" "text" DEFAULT 'MUR'::"text" NOT NULL,
    "number_prefix" "text" DEFAULT 'INV'::"text" NOT NULL,
    "number_padding" integer DEFAULT 4 NOT NULL,
    "next_number" integer DEFAULT 1 NOT NULL,
    "payment_terms" integer DEFAULT 14 NOT NULL,
    "default_notes" "text",
    "default_terms" "text",
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "quotation_prefix" "text" DEFAULT 'QT'::"text" NOT NULL,
    "quotation_number_padding" integer DEFAULT 4 NOT NULL,
    "quotation_next_number" integer DEFAULT 1 NOT NULL,
    "sales_order_prefix" "text" DEFAULT 'SO'::"text" NOT NULL,
    "sales_order_number_padding" integer DEFAULT 4 NOT NULL,
    "sales_order_next_number" integer DEFAULT 1 NOT NULL,
    "purchase_order_prefix" "text" DEFAULT 'PO'::"text" NOT NULL,
    "purchase_order_number_padding" integer DEFAULT 4 NOT NULL,
    "purchase_order_next_number" integer DEFAULT 1 NOT NULL,
    "purchase_invoice_prefix" "text" DEFAULT 'PINV'::"text" NOT NULL,
    "purchase_invoice_number_padding" integer DEFAULT 4 NOT NULL,
    "purchase_invoice_next_number" integer DEFAULT 1 NOT NULL,
    "company_id" "uuid",
    "credit_note_prefix" "text" DEFAULT 'CN'::"text" NOT NULL,
    "credit_note_number_padding" integer DEFAULT 4 NOT NULL,
    "credit_note_next_number" integer DEFAULT 1 NOT NULL,
    CONSTRAINT "user_settings_purchase_invoice_next_number_check" CHECK (("purchase_invoice_next_number" >= 1)),
    CONSTRAINT "user_settings_purchase_invoice_number_padding_check" CHECK ((("purchase_invoice_number_padding" >= 1) AND ("purchase_invoice_number_padding" <= 10))),
    CONSTRAINT "user_settings_purchase_order_next_number_check" CHECK (("purchase_order_next_number" >= 1)),
    CONSTRAINT "user_settings_purchase_order_number_padding_check" CHECK ((("purchase_order_number_padding" >= 1) AND ("purchase_order_number_padding" <= 10))),
    CONSTRAINT "user_settings_quotation_next_number_check" CHECK (("quotation_next_number" >= 1)),
    CONSTRAINT "user_settings_quotation_number_padding_check" CHECK ((("quotation_number_padding" >= 1) AND ("quotation_number_padding" <= 10))),
    CONSTRAINT "user_settings_sales_order_next_number_check" CHECK (("sales_order_next_number" >= 1)),
    CONSTRAINT "user_settings_sales_order_number_padding_check" CHECK ((("sales_order_number_padding" >= 1) AND ("sales_order_number_padding" <= 10)))
);
CREATE TABLE IF NOT EXISTS "public"."whatsapp_ad_click_stats" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "company" "text" NOT NULL,
    "ad_id" "text" NOT NULL,
    "stat_date" "date" NOT NULL,
    "meta_clicks" integer DEFAULT 0 NOT NULL,
    "meta_conversations_started" integer DEFAULT 0 NOT NULL,
    "synced_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "whatsapp_ad_click_stats_company_check" CHECK (("company" = ANY (ARRAY['spark'::"text", 'sodamax'::"text"])))
);
CREATE TABLE IF NOT EXISTS "public"."whatsapp_ad_referrals" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "company" "text" NOT NULL,
    "phone" "text" NOT NULL,
    "source_id" "text",
    "source_url" "text",
    "source_type" "text",
    "received_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "whatsapp_ad_referrals_company_check" CHECK (("company" = ANY (ARRAY['spark'::"text", 'sodamax'::"text"])))
);
CREATE TABLE IF NOT EXISTS "public"."whatsapp_bot_item_colors" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "item_id" "uuid" NOT NULL,
    "color_name" "text" NOT NULL,
    "color_hex" "text",
    "sort_order" integer DEFAULT 0 NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);
CREATE TABLE IF NOT EXISTS "public"."whatsapp_bot_items" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "ad_link" "text",
    "image_base64" "text",
    "description" "text",
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "product_name" "text",
    "price" "text",
    "company" "text" DEFAULT 'spark'::"text" NOT NULL,
    "price_amount" numeric DEFAULT 0,
    "sort_order" integer DEFAULT 0 NOT NULL,
    "ad_link_2" "text",
    "ad_id" "text",
    "ad_id_2" "text",
    "is_website" boolean DEFAULT true,
    "is_whatsapp" boolean DEFAULT true,
    "source" "text",
    CONSTRAINT "whatsapp_bot_items_company_check" CHECK (("company" = ANY (ARRAY['spark'::"text", 'sodamax'::"text"]))),
    CONSTRAINT "whatsapp_bot_items_price_amount_check" CHECK (("price_amount" >= (0)::numeric))
);
CREATE TABLE IF NOT EXISTS "public"."whatsapp_bot_orders" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "customer_name" "text" NOT NULL,
    "product_name" "text" NOT NULL,
    "quantity" integer DEFAULT 1 NOT NULL,
    "city" "text" NOT NULL,
    "address" "text" NOT NULL,
    "total" numeric(12,2) DEFAULT 0 NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "customer_phone_number" "text" NOT NULL,
    "order_ref" "text" NOT NULL,
    "status" "text" DEFAULT 'pending'::"text" NOT NULL,
    "company" "text" DEFAULT 'spark'::"text" NOT NULL,
    "city_id" "uuid",
    "notes" "text",
    "source" "text",
    CONSTRAINT "whatsapp_bot_orders_company_check" CHECK (("company" = ANY (ARRAY['spark'::"text", 'sodamax'::"text"]))),
    CONSTRAINT "whatsapp_bot_orders_status_check" CHECK (("status" = ANY (ARRAY['draft'::"text", 'complete'::"text", 'approved'::"text", 'rejected'::"text"])))
);
CREATE TABLE IF NOT EXISTS "public"."whatsapp_bot_orders_items" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "order_id" "uuid" NOT NULL,
    "item_id" "uuid",
    "product_name" "text" NOT NULL,
    "quantity" integer DEFAULT 1 NOT NULL,
    "unit_price" numeric(12,2) DEFAULT 0 NOT NULL,
    "line_total" numeric(12,2) DEFAULT 0 NOT NULL,
    "sort_order" integer DEFAULT 0 NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "color_id" "uuid",
    "color_name" "text",
    "color_hex" "text",
    CONSTRAINT "whatsapp_bot_orders_items_line_total_check" CHECK (("line_total" >= (0)::numeric)),
    CONSTRAINT "whatsapp_bot_orders_items_quantity_check" CHECK (("quantity" > 0)),
    CONSTRAINT "whatsapp_bot_orders_items_unit_price_check" CHECK (("unit_price" >= (0)::numeric))
);
CREATE TABLE IF NOT EXISTS "public"."whatsapp_catalogue_posts" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "company_id" "uuid" NOT NULL,
    "user_id" "uuid" NOT NULL,
    "description" "text" DEFAULT ''::"text" NOT NULL,
    "image_base64" "text",
    "image_mime_type" "text",
    "sort_order" integer DEFAULT 0 NOT NULL,
    "is_active" boolean DEFAULT true NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "whatsapp_catalogue_posts_image_mime_check" CHECK ((("image_mime_type" IS NULL) OR ("image_mime_type" = ANY (ARRAY['image/png'::"text", 'image/jpeg'::"text", 'image/webp'::"text", 'image/gif'::"text"])))),
    CONSTRAINT "whatsapp_catalogue_posts_image_pair_check" CHECK (((("image_base64" IS NULL) AND ("image_mime_type" IS NULL)) OR (("image_base64" IS NOT NULL) AND ("image_mime_type" IS NOT NULL)))),
    CONSTRAINT "whatsapp_catalogue_posts_image_size_check" CHECK ((("image_base64" IS NULL) OR ("octet_length"("image_base64") <= 5242880)))
);
CREATE TABLE IF NOT EXISTS "public"."whatsapp_group_customers" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "company_id" "uuid" NOT NULL,
    "whatsapp_group_id" "uuid" NOT NULL,
    "customer_id" "uuid" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);
CREATE TABLE IF NOT EXISTS "public"."whatsapp_groups" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "company_id" "uuid" NOT NULL,
    "user_id" "uuid" NOT NULL,
    "name" "text" NOT NULL,
    "description" "text",
    "is_active" boolean DEFAULT true NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);
CREATE TABLE IF NOT EXISTS "public"."whatsapp_inbound_dedup" (
    "message_id" "text" NOT NULL,
    "phone" "text" NOT NULL,
    "company" "text" DEFAULT 'spark'::"text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);
CREATE TABLE IF NOT EXISTS "public"."whatsapp_scheduled_promos" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "phone" "text" NOT NULL,
    "company" "text" NOT NULL,
    "kind" "text" DEFAULT 'flavour_promo'::"text" NOT NULL,
    "send_at" timestamp with time zone NOT NULL,
    "sent_at" timestamp with time zone,
    "error" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "order_id" "uuid",
    CONSTRAINT "whatsapp_scheduled_promos_company_check" CHECK (("company" = ANY (ARRAY['spark'::"text", 'sodamax'::"text"])))
);
CREATE TABLE IF NOT EXISTS "public"."whatsapp_session_cart_items" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "phone" "text" NOT NULL,
    "company" "text" NOT NULL,
    "item_id" "uuid" NOT NULL,
    "color_id" "uuid",
    "quantity" integer DEFAULT 1 NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "whatsapp_session_cart_items_quantity_check" CHECK (("quantity" > 0))
);
CREATE TABLE IF NOT EXISTS "public"."whatsapp_sessions" (
    "phone" "text" NOT NULL,
    "state" "text" DEFAULT 'idle'::"text" NOT NULL,
    "selected_item_id" "uuid",
    "quantity" integer,
    "city" "text",
    "address" "text",
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "customer_name" "text",
    "total" numeric,
    "draft_order_id" "uuid",
    "reminder_count" integer DEFAULT 0 NOT NULL,
    "last_inbound_at" timestamp with time zone,
    "last_reminder_at" timestamp with time zone,
    "company" "text" DEFAULT 'spark'::"text" NOT NULL,
    "region" "text",
    "message_status" "public"."whatsapp_message_status",
    "message_notes" "text",
    "converted_order_id" "uuid",
    CONSTRAINT "whatsapp_sessions_company_check" CHECK (("company" = ANY (ARRAY['spark'::"text", 'sodamax'::"text"])))
);
CREATE TABLE IF NOT EXISTS "public"."worker_applications" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid",
    "first_name" "text" NOT NULL,
    "last_name" "text" NOT NULL,
    "worker_kind" "public"."worker_kind" NOT NULL,
    "phone" "text" NOT NULL,
    "email" "text",
    "job_types" "text"[] NOT NULL,
    "other_job_type" "text",
    "years_experience" smallint NOT NULL,
    "district" "text" NOT NULL,
    "areas_served" "text",
    "services_offered" "text"[] DEFAULT '{}'::"text"[] NOT NULL,
    "subscription_plan" "public"."subscription_plan" NOT NULL,
    "bio" "text" NOT NULL,
    "terms_accepted_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "profile_status" "public"."worker_profile_status" DEFAULT 'pending'::"public"."worker_profile_status" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "worker_applications_job_types_check" CHECK (("cardinality"("job_types") >= 1)),
    CONSTRAINT "worker_applications_years_experience_check" CHECK (("years_experience" >= 0))
);
CREATE TABLE IF NOT EXISTS "public"."worker_monthly_payments" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "worker_application_id" "uuid" NOT NULL,
    "year" smallint NOT NULL,
    "month" smallint NOT NULL,
    "status" "text" DEFAULT 'unpaid'::"text" NOT NULL,
    "paid_at" timestamp with time zone,
    "note" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "worker_monthly_payments_month_check" CHECK ((("month" >= 1) AND ("month" <= 12))),
    CONSTRAINT "worker_monthly_payments_status_check" CHECK (("status" = ANY (ARRAY['unpaid'::"text", 'paid'::"text", 'pending'::"text"]))),
    CONSTRAINT "worker_monthly_payments_year_check" CHECK ((("year" >= 2020) AND ("year" <= 2100)))
);
CREATE TABLE IF NOT EXISTS "public"."zone_cities" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "company_id" "uuid" NOT NULL,
    "zone_id" "uuid" NOT NULL,
    "city_id" "uuid" NOT NULL,
    "sort_order" integer NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "zone_cities_sort_order_positive" CHECK (("sort_order" > 0))
);
CREATE TABLE IF NOT EXISTS "public"."zones" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "company_id" "uuid" NOT NULL,
    "driver_user_id" "uuid",
    "name" "text" NOT NULL,
    "description" "text",
    "is_active" boolean DEFAULT true NOT NULL,
    "created_by" "uuid",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);
